[buildPlans.IosevkaDx4]
family = "Iosevka DX4"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaDx4.variants.design]
four = "closed-serifless"
eight = "crossing-asymmetric"
capital-g = "toothless-corner-serifless-hooked"
capital-q = "crossing"
m = "short-leg-serifless"
lower-lambda = "straight-turn"
brace = "straight"
percent = "dots"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.IosevkaDx4.variants.italic]
four = "closed-serifless"
eight = "crossing-asymmetric"
capital-g = "toothless-corner-serifless-hooked"
capital-q = "crossing"
b = "toothless-corner-serifless"
k = "straight-serifless"
m = "short-leg-serifless"
w = "rounded-vertical-sides-serifless"
lower-lambda = "straight-turn"
brace = "straight"
percent = "dots"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.IosevkaDx4.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaDx4.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaDx4.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaDx4.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaDx4.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IosevkaDx4.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaDx4.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaDx4.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
